In [2]:
import numpy as np
import pandas as pd

In [3]:
#importing the data
dataset=pd.read_excel("a1_Dataset_10Percent.xlsx")
print(dataset)

             ID  DemAffl  DemAge DemClusterGroup DemGender      DemReg  \
0      17147654      5.0     NaN             NaN       NaN         NaN   
1       8415498     15.0     NaN             NaN         M         NaN   
2      12107603      NaN     NaN             NaN         M    Midlands   
3      14400995      8.0    28.0             NaN         F         NaN   
4      28724674     14.0    67.0             NaN       NaN         NaN   
...         ...      ...     ...             ...       ...         ...   
22218  52830893     13.0    49.0               B         M  South East   
22219  52834058     13.0    65.0               B         F  South East   
22220  52834376     15.0    73.0               D         U  South East   
22221  52837057      9.0    70.0               B         F       North   
22222  52838096     11.0    66.0               B         F       North   

         DemTVReg LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0             NaN        Tin        0.01      

In [4]:
#droping the id column from the dataset
dataset=dataset.drop(['ID'],axis=1)
dataset.head()

DemAffl  DemAge DemClusterGroup DemGender    DemReg DemTVReg LoyalClass  \
0      5.0     NaN             NaN       NaN       NaN      NaN        Tin   
1     15.0     NaN             NaN         M       NaN      NaN       Gold   
2      NaN     NaN             NaN         M  Midlands     East        Tin   
3      8.0    28.0             NaN         F       NaN      NaN        Tin   
4     14.0    67.0             NaN       NaN       NaN      NaN        Tin   

   LoyalSpend  LoyalTime  TargetBuy  
0        0.01        5.0          0  
1     8000.00        5.0          1  
2        0.01        NaN          1  
3        0.01        NaN          1  
4        0.01        7.0          0

In [5]:
#calculating the number of missing values 
dataset.isna().sum()

DemAffl            1085
DemAge             1508
DemClusterGroup     674
DemGender          2512
DemReg              465
DemTVReg            465
LoyalClass            0
LoyalSpend            0
LoyalTime           281
TargetBuy             0
dtype: int64

In [6]:
#filing up the missing values
dataset['DemAffl']=dataset['DemAffl'].fillna(dataset['DemAffl'].mode()[0])
dataset['DemAge']=dataset['DemAge'].fillna(dataset['DemAge'].mode()[0])
dataset['DemClusterGroup']=dataset['DemClusterGroup'].fillna(dataset['DemClusterGroup'].mode()[0])
dataset['DemGender']=dataset['DemGender'].fillna(dataset['DemGender'].mode()[0])
dataset['DemReg']=dataset['DemReg'].fillna(dataset['DemReg'].mode()[0])
dataset['DemTVReg']=dataset['DemTVReg'].fillna(dataset['DemTVReg'].mode()[0])
dataset['LoyalTime']=dataset['LoyalTime'].fillna(dataset['LoyalTime'].mean())

In [7]:
dataset.isna().sum()

DemAffl            0
DemAge             0
DemClusterGroup    0
DemGender          0
DemReg             0
DemTVReg           0
LoyalClass         0
LoyalSpend         0
LoyalTime          0
TargetBuy          0
dtype: int64

In [8]:
#encoding the data
from sklearn.preprocessing import LabelEncoder
number=LabelEncoder()

dataset['DemClusterGroup']=number.fit_transform(dataset['DemClusterGroup'].astype('str'))
integer_mapping={l:i for i,l in enumerate(number.classes_)}
print(integer_mapping)

dataset['DemGender']=number.fit_transform(dataset['DemGender'].astype('str'))
integer_mapping={l:i for i,l in enumerate(number.classes_)}
print(integer_mapping)

dataset['DemReg']=number.fit_transform(dataset['DemReg'].astype('str'))
integer_mapping={l:i for i,l in enumerate(number.classes_)}
print(integer_mapping)

dataset['DemTVReg']=number.fit_transform(dataset['DemTVReg'].astype('str'))
integer_mapping={l:i for i,l in enumerate(number.classes_)}
print(integer_mapping)

dataset['LoyalClass']=number.fit_transform(dataset['LoyalClass'].astype('str'))
integer_mapping={l:i for i,l in enumerate(number.classes_)}
print(integer_mapping)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'U': 6}
{'F': 0, 'M': 1, 'U': 2}
{'Midlands': 0, 'North': 1, 'Scottish': 2, 'South East': 3, 'South West': 4}
{'Border': 0, 'C Scotland': 1, 'East': 2, 'London': 3, 'Midlands': 4, 'N East': 5, 'N Scot': 6, 'N West': 7, 'S & S East': 8, 'S West': 9, 'Ulster': 10, 'Wales & West': 11, 'Yorkshire': 12}
{'Gold': 0, 'Platinum': 1, 'Silver': 2, 'Tin': 3}


In [9]:
dataset.head()

DemAffl  DemAge  DemClusterGroup  DemGender  DemReg  DemTVReg  LoyalClass  \
0      5.0    51.0                2          0       3         3           3   
1     15.0    51.0                2          1       3         3           0   
2      8.0    51.0                2          1       0         2           3   
3      8.0    28.0                2          0       3         3           3   
4     14.0    67.0                2          0       3         3           3   

   LoyalSpend  LoyalTime  TargetBuy  
0        0.01    5.00000          0  
1     8000.00    5.00000          1  
2        0.01    6.56467          1  
3        0.01    6.56467          1  
4        0.01    7.00000          0

In [10]:
x=dataset.iloc[:, 0:9].values
y=dataset.iloc[:, 9].values

In [11]:
print(x)

[[5.00000000e+00 5.10000000e+01 2.00000000e+00 ... 3.00000000e+00
  1.00000000e-02 5.00000000e+00]
 [1.50000000e+01 5.10000000e+01 2.00000000e+00 ... 0.00000000e+00
  8.00000000e+03 5.00000000e+00]
 [8.00000000e+00 5.10000000e+01 2.00000000e+00 ... 3.00000000e+00
  1.00000000e-02 6.56467049e+00]
 ...
 [1.50000000e+01 7.30000000e+01 3.00000000e+00 ... 0.00000000e+00
  6.05306000e+03 1.20000000e+01]
 [9.00000000e+00 7.00000000e+01 1.00000000e+00 ... 0.00000000e+00
  6.00000000e+03 5.00000000e+00]
 [1.10000000e+01 6.60000000e+01 1.00000000e+00 ... 2.00000000e+00
  5.00000000e+03 5.00000000e+00]]


In [12]:
print(y)

[0 1 1 ... 0 0 0]


In [13]:
#Splliting the data into train set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
print(x_train)

[[8.000000e+00 7.700000e+01 0.000000e+00 ... 0.000000e+00 1.200000e+04
  1.300000e+01]
 [7.000000e+00 3.100000e+01 4.000000e+00 ... 2.000000e+00 5.000000e+02
  9.000000e+00]
 [7.000000e+00 7.000000e+01 5.000000e+00 ... 0.000000e+00 1.734564e+04
  3.000000e+00]
 ...
 [8.000000e+00 7.600000e+01 3.000000e+00 ... 0.000000e+00 1.610670e+04
  6.000000e+00]
 [7.000000e+00 7.500000e+01 5.000000e+00 ... 0.000000e+00 6.107640e+03
  5.000000e+00]
 [5.000000e+00 4.100000e+01 3.000000e+00 ... 3.000000e+00 1.000000e-02
  5.000000e+00]]


In [15]:
print(y_train)

[0 1 0 ... 1 0 0]


In [16]:
print(x_test)

[[1.000000e+01 5.800000e+01 3.000000e+00 ... 0.000000e+00 1.263266e+04
  4.000000e+00]
 [1.000000e+01 5.100000e+01 2.000000e+00 ... 0.000000e+00 6.000000e+03
  6.000000e+00]
 [1.600000e+01 6.500000e+01 1.000000e+00 ... 0.000000e+00 6.053350e+03
  7.000000e+00]
 ...
 [1.000000e+01 6.200000e+01 0.000000e+00 ... 0.000000e+00 6.000000e+03
  4.000000e+00]
 [7.000000e+00 5.400000e+01 3.000000e+00 ... 0.000000e+00 9.250000e+03
  2.000000e+00]
 [5.000000e+00 5.400000e+01 5.000000e+00 ... 3.000000e+00 1.000000e-02
  6.000000e+00]]


In [17]:
print(y_test)

[0 0 0 ... 0 0 0]


In [18]:
#building logistic regression model
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

c:\Program Files\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [19]:
#predicting the result
y_pred=classifier.predict(x_test)
print(y_pred)

[0 0 1 ... 0 0 0]


In [20]:
# Exporting Logistic Regression Classifier to later use in prediction
import joblib
joblib.dump(classifier, './c2_Classifier_LoyalCustomers')

['./c2_Classifier_LoyalCustomers']

In [21]:
#confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
ac=accuracy_score(y_pred,y_test)

In [22]:
print(cm)

[[3213  694]
 [ 154  384]]


In [23]:
print(ac)

0.8092238470191226


In [24]:
#calculating the probablity of x_test
predictions=classifier.predict_proba(x_test)
print(predictions)

[[0.84448023 0.15551977]
 [0.64370875 0.35629125]
 [0.4271054  0.5728946 ]
 ...
 [0.81544903 0.18455097]
 [0.90173316 0.09826684]
 [0.91797705 0.08202295]]


In [25]:
# writing model output file

df_prediction_prob = pd.DataFrame(predictions, columns = ['prob_0', 'prob_1'])
df_test_dataset = pd.DataFrame(y_test,columns= ['Actual Outcome'])
df_x_test = pd.DataFrame(x_test)

dfx=pd.concat([df_x_test,df_test_dataset, df_prediction_prob], axis=1)

dfx.to_excel("ModelOutput_10Percent.xlsx")

dfx.head()


0     1    2    3    4    5    6         7    8  Actual Outcome  \
0  10.0  58.0  3.0  1.0  3.0  8.0  0.0  12632.66  4.0               0   
1  10.0  51.0  2.0  0.0  3.0  8.0  0.0   6000.00  6.0               0   
2  16.0  65.0  1.0  0.0  2.0  6.0  0.0   6053.35  7.0               0   
3   5.0  60.0  3.0  0.0  3.0  3.0  2.0   5000.00  1.0               0   
4   9.0  52.0  3.0  0.0  0.0  4.0  2.0   3500.00  6.0               0   

     prob_0    prob_1  
0  0.844480  0.155520  
1  0.643709  0.356291  
2  0.427105  0.572895  
3  0.933296  0.066704  
4  0.719300  0.280700